name: Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 5
    env:
      ANAPLAN_CERT: ${{ secrets.ANAPLAN_CERT }}
      ANAPLAN_PK: ${{ secrets.ANAPLAN_PK }}

    name: Python ${{ matrix.python-version }}
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm

    strategy:
      max-parallel: 20
      matrix:
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
      - name: Setup Python
        run: uv python install
      - name: Setup Project
        run: uv sync --dev
      - name: Run tests
        run: uv run python -m pytest tests/
